



CREATE TABLE AGENDA (
    ID INTEGER NOT NULL,
    NOME D_NOME NOT NULL,
    TIPO SMALLINT NOT NULL);

ALTER TABLE AGENDA
ADD CONSTRAINT PK_AGENDA
PRIMARY KEY (ID);

COMMENT ON COLUMN AGENDA.TIPO IS
'Tipo desta agenda
0 - Pessoal
1 - Outro';

CREATE SEQUENCE GEN_AGENDA;



CREATE TABLE AGENDA_PESSOA (
    ID INTEGER NOT NULL,
    ID_AGENDA INTEGER NOT NULL,
    ID_PESSOA INTEGER NOT NULL,
    SOMENTE_VISUALIZACAO SMALLINT NOT NULL);

ALTER TABLE AGENDA_PESSOA
ADD CONSTRAINT PK_AGENDA_PESSOA
PRIMARY KEY (ID);

COMMENT ON COLUMN AGENDA_PESSOA.SOMENTE_VISUALIZACAO IS
'0 - Nao
1 - Sim';

CREATE SEQUENCE GEN_AGENDA_PESSOA;



CREATE TABLE AGENDA_REGISTRO (
    ID INTEGER NOT NULL,
    TITULO VARCHAR(150) CHARACTER SET WIN1252 NOT NULL,
    DESCRICAO D_DESCRICAO,
    DATA_INICIO DATE NOT NULL,
    DATA_FIM DATE NOT NULL,
    HORA_INICIO TIME,
    HORA_FIM INTEGER);

ALTER TABLE AGENDA_REGISTRO
ADD CONSTRAINT PK_AGENDA_REGISTRO
PRIMARY KEY (ID);

CREATE SEQUENCE GEN_AGENDA_REGISTRO;



ALTER TABLE AGENDA_PESSOA
ADD CONSTRAINT FK_AGENDA_PESSOA_1
FOREIGN KEY (ID_AGENDA)
REFERENCES AGENDA(ID)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE AGENDA_PESSOA
ADD CONSTRAINT FK_AGENDA_PESSOA_2
FOREIGN KEY (ID_PESSOA)
REFERENCES PESSOA(ID)
ON UPDATE CASCADE;

