

ALTER TABLE ESPECIE
    ADD INICIO_PERIODO_COLETA DATE,
    ADD FIM_PERIODO_COLETA DATE;

COMMENT ON COLUMN ESPECIE.INICIO_PERIODO_COLETA IS
'Inicio do periodo ideal para realizar a coleta das sementes';

COMMENT ON COLUMN ESPECIE.FIM_PERIODO_COLETA IS
'Fim do periodo ideal para realizar a coleta das sementes';



CREATE TABLE LOTE_SEMENTE (
    ID                 INTEGER NOT NULL,
    ID_ESPECIE         INTEGER NOT NULL,
    ID_PESSOA_COLETOU  INTEGER NOT NULL,
    NOME               VARCHAR(30) NOT NULL,
    DATA               DATE NOT NULL,
    QTDE               NUMERIC(15,2) NOT NULL,
    QTDE_ARMAZENADA    NUMERIC(15,2),
    TAXA_GERMINACAO    NUMERIC(15,2),
    TAXA_DESCARTE      COMPUTED BY (100-TAXA_GERMINACAO),
    STATUS             SMALLINT
);


ALTER TABLE LOTE_SEMENTE ADD CONSTRAINT PK_LOTE_SEMENTE PRIMARY KEY (ID);


ALTER TABLE LOTE_SEMENTE ADD CONSTRAINT FK_LOTE_SEMENTE_1 FOREIGN KEY (ID_PESSOA_COLETOU) REFERENCES PESSOA (ID) ON UPDATE CASCADE;
ALTER TABLE LOTE_SEMENTE ADD CONSTRAINT FK_LOTE_SEMENTE_2 FOREIGN KEY (ID_ESPECIE) REFERENCES ESPECIE (ID) ON UPDATE CASCADE;


COMMENT ON COLUMN LOTE_SEMENTE.DATA IS
'Data de coleta ou da compra';

COMMENT ON COLUMN LOTE_SEMENTE.QTDE IS
'Qtde de sementes coletadas/compradas em kilos';

COMMENT ON COLUMN LOTE_SEMENTE.QTDE_ARMAZENADA IS
'Qtde em kilos de sementes em estoque';

COMMENT ON COLUMN LOTE_SEMENTE.TAXA_GERMINACAO IS
'Percentual de germinacao desse lote';

COMMENT ON COLUMN LOTE_SEMENTE.TAXA_DESCARTE IS
'Taxa de descarte desse lote (100 - Taxa de Germinacao)';

COMMENT ON COLUMN LOTE_SEMENTE.STATUS IS
'0|NULL - Aberto (Processo de semeadura e germinacao em andamento)
1 - Fechado (Semeadura e germinacao finalizados)';



CREATE TABLE LOTE_SEMENTE_MATRIZ (
    ID         INTEGER NOT NULL,
    ID_LOTE    INTEGER NOT NULL,
    ID_MATRIZ  INTEGER NOT NULL
);

ALTER TABLE LOTE_SEMENTE_MATRIZ ADD CONSTRAINT PK_LOTE_SEMENTE_MATRIZ PRIMARY KEY (ID);

ALTER TABLE LOTE_SEMENTE_MATRIZ ADD CONSTRAINT FK_LOTE_SEMENTE_MATRIZ_1 FOREIGN KEY (ID_LOTE) REFERENCES LOTE_SEMENTE (ID) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE LOTE_SEMENTE_MATRIZ ADD CONSTRAINT FK_LOTE_SEMENTE_MATRIZ_2 FOREIGN KEY (ID_MATRIZ) REFERENCES MATRIZ (ID) ON UPDATE CASCADE;


delete from lote;

delete from germinacao;

delete from semeadura;

DROP TABLE LOTE_MATRIZ;








ALTER TABLE GERMINACAO DROP CONSTRAINT FK_GERMINACAO_1;



ALTER TABLE GERMINACAO ALTER ID_LOTE TO ID_LOTE_SEMENTE;



ALTER TABLE GERMINACAO
ADD CONSTRAINT FK_GERMINACAO_1
FOREIGN KEY (ID_LOTE_SEMENTE)
REFERENCES LOTE_SEMENTE(ID)
ON DELETE CASCADE
ON UPDATE CASCADE;



ALTER TABLE SEMEADURA DROP CONSTRAINT FK_SEMEADURA_1;



ALTER TABLE SEMEADURA ALTER ID_LOTE TO ID_LOTE_SEMEADURA;



ALTER TABLE SEMEADURA ALTER ID_LOTE_SEMEADURA TO ID_LOTE_SEMENTE;



ALTER TABLE SEMEADURA
ADD CONSTRAINT FK_SEMEADURA_1
FOREIGN KEY (ID_LOTE_SEMENTE)
REFERENCES LOTE_SEMENTE(ID)
ON DELETE CASCADE
ON UPDATE CASCADE;



DROP TABLE LOTE;



ALTER TABLE LOTE_SEMENTE_MATRIZ DROP CONSTRAINT FK_LOTE_SEMENTE_MATRIZ_1;



ALTER TABLE LOTE_SEMENTE_MATRIZ ALTER ID_LOTE TO ID_LOTE_SEMENTE;



ALTER TABLE LOTE_SEMENTE_MATRIZ
ADD CONSTRAINT FK_LOTE_SEMENTE_MATRIZ_1
FOREIGN KEY (ID_LOTE_SEMENTE)
REFERENCES LOTE_SEMENTE(ID)
ON DELETE CASCADE
ON UPDATE CASCADE;



DROP SEQUENCE GEN_LOTE;

CREATE SEQUENCE GEN_LOTE_SEMENTE;



DROP SEQUENCE GEN_LOTE_MATRIZ;

CREATE SEQUENCE GEN_LOTE_SEMENTE_MATRIZ;

ALTER SEQUENCE GEN_LOTE_SEMENTE_MATRIZ RESTART WITH 15;



ALTER TABLE SEMEADURA
    ADD QTDE_TUBETE INTEGER;

COMMENT ON COLUMN SEMEADURA.QTDE_TUBETE IS
'Qtde. tubetes semeados';



update RDB$RELATION_FIELDS set
RDB$NULL_FLAG = 1
where (RDB$FIELD_NAME = 'QTDE_TUBETE') and
(RDB$RELATION_NAME = 'SEMEADURA')
;



alter table SEMEADURA
alter ID position 1;

alter table SEMEADURA
alter ID_LOTE_SEMENTE position 2;

alter table SEMEADURA
alter ID_PESSOA_SEMEOU position 3;

alter table SEMEADURA
alter ID_CANTEIRO position 4;

alter table SEMEADURA
alter QTDE_SEMEADA position 5;

alter table SEMEADURA
alter QTDE_TUBETE position 6;

alter table SEMEADURA
alter DATA position 7;

alter table SEMEADURA
alter DATA_PREVISTA_GERMINACAO position 8;

alter table SEMEADURA
alter OBSERVACAO position 9;



CREATE TABLE LOTE_MUDA (
    ID INTEGER NOT NULL,
    ID_ESPECIE INTEGER NOT NULL,
    NOME D_NOME NOT NULL,
    QTDE INTEGER NOT NULL,
    QTDE_INICIAL INTEGER NOT NULL,
    DATA TIMESTAMP NOT NULL);

ALTER TABLE LOTE_MUDA
ADD CONSTRAINT PK_LOTE_MUDA
PRIMARY KEY (ID);

COMMENT ON COLUMN LOTE_MUDA.QTDE IS
'Qtde atual de mudas no lote';

COMMENT ON COLUMN LOTE_MUDA.QTDE_INICIAL IS
'Qtde. inicial de mudas do lote';

COMMENT ON COLUMN LOTE_MUDA.DATA IS
'Data e Hora da inclusão do lote';

CREATE SEQUENCE GEN_LOTE_MUDA;



ALTER TABLE LOTE_MUDA
    ADD ID_PESSOA INTEGER;

COMMENT ON COLUMN LOTE_MUDA.ID_PESSOA IS
'Pessoa que incluiu o lote';

alter table LOTE_MUDA
alter ID position 1;

alter table LOTE_MUDA
alter ID_ESPECIE position 2;

alter table LOTE_MUDA
alter ID_PESSOA position 3;

alter table LOTE_MUDA
alter NOME position 4;

alter table LOTE_MUDA
alter QTDE position 5;

alter table LOTE_MUDA
alter QTDE_INICIAL position 6;

alter table LOTE_MUDA
alter DATA position 7;



ALTER TABLE LOTE_MUDA
ADD CONSTRAINT FK_LOTE_MUDA_2
FOREIGN KEY (ID_PESSOA)
REFERENCES PESSOA(ID)
ON UPDATE caSCADE;



ALTER TABLE LOTE_MUDA
    ADD OBSERVACAO D_DESCRICAO;



CREATE TABLE CLASSIFICACAO (
    ID INTEGER NOT NULL,
    ID_PESSOA_CLASSIFICOU INTEGER NOT NULL,
    DATA DATE NOT NULL,
    QTDE INTEGER NOT NULL,
    OBSERVACAO D_DESCRICAO);

ALTER TABLE CLASSIFICACAO
ADD CONSTRAINT PK_CLASSIFICACAO
PRIMARY KEY (ID);

COMMENT ON COLUMN CLASSIFICACAO.QTDE IS
'Qtde. de mudas ainda existentes';

CREATE SEQUENCE GEN_CLASSIFICACAO;



ALTER TABLE CLASSIFICACAO
    ADD ID_LOTE_MUDA INTEGER;

alter table CLASSIFICACAO
alter ID position 1;

alter table CLASSIFICACAO
alter ID_LOTE_MUDA position 2;

alter table CLASSIFICACAO
alter ID_PESSOA_CLASSIFICOU position 3;

alter table CLASSIFICACAO
alter DATA position 4;

alter table CLASSIFICACAO
alter QTDE position 5;

alter table CLASSIFICACAO
alter OBSERVACAO position 6;



ALTER TABLE CLASSIFICACAO
ADD CONSTRAINT FK_CLASSIFICACAO_1
FOREIGN KEY (ID_LOTE_MUDA)
REFERENCES LOTE_MUDA(ID)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE CLASSIFICACAO
ADD CONSTRAINT FK_CLASSIFICACAO_2
FOREIGN KEY (ID_PESSOA_CLASSIFICOU)
REFERENCES PESSOA(ID)
ON UPDATE CASCADE;



update RDB$RELATION_FIELDS set
RDB$NULL_FLAG = 1
where (RDB$FIELD_NAME = 'ID_LOTE_MUDA') and
(RDB$RELATION_NAME = 'CLASSIFICACAO')
;



ALTER TABLE LOTE_MUDA DROP ID_PESSOA;



ALTER TABLE LOTE_MUDA
    ADD ID_LOTE_SEMENTE INTEGER;

alter table LOTE_MUDA
alter ID position 1;

alter table LOTE_MUDA
alter ID_ESPECIE position 2;

alter table LOTE_MUDA
alter ID_LOTE_SEMENTE position 3;

alter table LOTE_MUDA
alter NOME position 4;

alter table LOTE_MUDA
alter QTDE position 5;

alter table LOTE_MUDA
alter QTDE_INICIAL position 6;

alter table LOTE_MUDA
alter DATA position 7;

alter table LOTE_MUDA
alter OBSERVACAO position 8;



ALTER TABLE LOTE_MUDA
ADD CONSTRAINT FK_LOTE_MUDA_2
FOREIGN KEY (ID_LOTE_SEMENTE)
REFERENCES LOTE_SEMENTE(ID)
ON UPDATE CASCADE;



ALTER DOMAIN D_DESCRICAO
TYPE VARCHAR(1000) CHARACTER SET WIN1252;



ALTER TABLE LOTE_MUDA DROP QTDE;



ALTER TABLE LOTE_MUDA
    ALTER DATA TYPE DATE;



ALTER TABLE GERMINACAO
    ALTER DATA TYPE DATE;



ALTER TABLE FIN_FOR_CLI
    ADD CARGO_CONTATO D_NOME;

alter table FIN_FOR_CLI
alter ID position 1;

alter table FIN_FOR_CLI
alter ID_CONTATO position 2;

alter table FIN_FOR_CLI
alter ID_CIDADE position 3;

alter table FIN_FOR_CLI
alter NOME_FANTASIA position 4;

alter table FIN_FOR_CLI
alter RAZAO_SOCIAL position 5;

alter table FIN_FOR_CLI
alter CARGO_CONTATO position 6;

alter table FIN_FOR_CLI
alter ENDERECO position 7;

alter table FIN_FOR_CLI
alter BAIRRO position 8;

alter table FIN_FOR_CLI
alter COMPLEMENTO position 9;

alter table FIN_FOR_CLI
alter TIPO position 10;

alter table FIN_FOR_CLI
alter TELEFONE position 11;

alter table FIN_FOR_CLI
alter CELULAR position 12;

alter table FIN_FOR_CLI
alter EMAIL position 13;

alter table FIN_FOR_CLI
alter SITE position 14;

alter table FIN_FOR_CLI
alter CPF_CNPJ position 15;

alter table FIN_FOR_CLI
alter INSCRICAO_ESTADUAL position 16;

alter table FIN_FOR_CLI
alter INSCRICAO_MUNICIPAL position 17;

alter table FIN_FOR_CLI
alter RAMO_ATIVIDADE position 18;

alter table FIN_FOR_CLI
alter PESQUISA position 19;

alter table FIN_FOR_CLI
alter OBSERVACAO position 20;



CREATE TABLE AREA_CUSTO (
    ID INTEGER NOT NULL,
    NOME D_NOME NOT NULL);

ALTER TABLE AREA_CUSTO
ADD CONSTRAINT PK_AREA_CUSTO
PRIMARY KEY (ID);

CREATE SEQUENCE GEN_AREA_CUSTO;



CREATE TABLE RUBRICA (
    ID INTEGER NOT NULL);

ALTER TABLE RUBRICA
ADD CONSTRAINT PK_RUBRICA
PRIMARY KEY (ID);

CREATE SEQUENCE GEN_RUBRICA;



CREATE TABLE PLANO_CONTAS (
    ID INTEGER NOT NULL,
    ID_CONTA_PAI INTEGER,
    NOME INTEGER,
    TIPO SMALLINT);

ALTER TABLE PLANO_CONTAS
ADD CONSTRAINT PK_PLANO_CONTAS
PRIMARY KEY (ID);

COMMENT ON COLUMN PLANO_CONTAS.TIPO IS
'0|NULL - Despesa
1 - Receita';

CREATE SEQUENCE GEN_PLANO_CONTAS;



ALTER TABLE PLANO_CONTAS
ADD CONSTRAINT FK_PLANO_CONTAS_1
FOREIGN KEY (ID_CONTA_PAI)
REFERENCES PLANO_CONTAS(ID)
ON DELETE CASCADE
ON UPDATE CASCADE;



update RDB$RELATION_FIELDS set
RDB$NULL_FLAG = 1
where (RDB$FIELD_NAME = 'TIPO') and
(RDB$RELATION_NAME = 'PLANO_CONTAS')
;



update RDB$RELATION_FIELDS set
RDB$NULL_FLAG = 1
where (RDB$FIELD_NAME = 'NOME') and
(RDB$RELATION_NAME = 'PLANO_CONTAS')
;



COMMENT ON COLUMN PLANO_CONTAS.ID_CONTA_PAI IS
'Id da conta pai, caso tenha.';



DROP TABLE AREA_CUSTO;



ALTER TABLE PLANO_CONTAS DROP NOME;



ALTER TABLE PLANO_CONTAS
    ADD NOME D_NOME NOT NULL;

alter table PLANO_CONTAS
alter ID position 1;

alter table PLANO_CONTAS
alter ID_CONTA_PAI position 2;

alter table PLANO_CONTAS
alter NOME position 3;

alter table PLANO_CONTAS
alter TIPO position 4;



ALTER TABLE PLANO_CONTAS
    ADD IDENTIFICADOR VARCHAR(20) NOT NULL;

COMMENT ON COLUMN PLANO_CONTAS.IDENTIFICADOR IS
'Identificador numerico da conta. Exemplos:
1
1.1

5
5.1
5.2';



ALTER TABLE RUBRICA
    ADD NOME D_NOME NOT NULL,
    ADD VALOR NUMERIC(15,2);



update RDB$RELATION_FIELDS set
RDB$NULL_FLAG = 1
where (RDB$FIELD_NAME = 'VALOR') and
(RDB$RELATION_NAME = 'RUBRICA')
;



CREATE TABLE RUBRICA_PROJETO (
    ID INTEGER NOT NULL,
    ID_RUBRICA INTEGER NOT NULL,
    ID_PROJETO INTEGER NOT NULL);

ALTER TABLE RUBRICA_PROJETO
ADD CONSTRAINT PK_RUBRICA_PROJETO
PRIMARY KEY (ID);

CREATE SEQUENCE GEN_RUBRICA_PROJETO;



ALTER TABLE RUBRICA_PROJETO
ADD CONSTRAINT FK_RUBRICA_PROJETO_1
FOREIGN KEY (ID_RUBRICA)
REFERENCES RUBRICA(ID)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE RUBRICA_PROJETO
ADD CONSTRAINT FK_RUBRICA_PROJETO_2
FOREIGN KEY (ID_PROJETO)
REFERENCES PROJETO(ID)
ON UPDATE CASCADE;



ALTER TABLE RUBRICA_PROJETO
    ADD ORCAMENTO NUMERIC(15,2) NOT NULL;



ALTER TABLE RUBRICA DROP VALOR;



CREATE TABLE PROJETO_RUBRICA (
    ID INTEGER NOT NULL,
    ID_PROJETO INTEGER NOT NULL,
    ID_RUBRICA INTEGER NOT NULL,
    ORCAMENTO NUMERIC(15,2) NOT NULL);

ALTER TABLE PROJETO_RUBRICA
ADD CONSTRAINT PK_PROJETO_RUBRICA
PRIMARY KEY (ID);

CREATE SEQUENCE GEN_PROJETO_RUBRICA;



ALTER TABLE PROJETO_RUBRICA
ADD CONSTRAINT FK_PROJETO_RUBRICA_1
FOREIGN KEY (ID_PROJETO)
REFERENCES PROJETO(ID)
ON DELETE CASCADE
ON UPDATE CASCADE;



ALTER TABLE PROJETO_RUBRICA
ADD CONSTRAINT FK_PROJETO_RUBRICA_2
FOREIGN KEY (ID_RUBRICA)
REFERENCES RUBRICA(ID)
ON UPDATE CASCADE;



DROP TABLE RUBRICA_PROJETO;



ALTER TABLE RUBRICA
    ADD ID_RUBRICA_PAI INTEGER,
    ADD IDENTIFICADOR VARCHAR(20);

alter table RUBRICA
alter ID position 1;

alter table RUBRICA
alter ID_RUBRICA_PAI position 2;

alter table RUBRICA
alter NOME position 3;

alter table RUBRICA
alter IDENTIFICADOR position 4;



ALTER TABLE RUBRICA
ADD CONSTRAINT FK_RUBRICA_1
FOREIGN KEY (ID_RUBRICA_PAI)
REFERENCES RUBRICA(ID)
ON DELETE CASCADE
ON UPDATE CASCADE;



update RDB$RELATION_FIELDS set
RDB$NULL_FLAG = 1
where (RDB$FIELD_NAME = 'IDENTIFICADOR') and
(RDB$RELATION_NAME = 'RUBRICA')
;



CREATE TABLE CONTA_PAGAR (
    ID INTEGER NOT NULL,
    ID_FORNECEDOR INTEGER NOT NULL,
    ID_RUBRICA INTEGER,
    ID_PLANO_CONTAS INTEGER NOT NULL,
    ID_CONTA_CORRENTE INTEGER,
    NOME D_NOME NOT NULL,
    VALOR_TOTAL NUMERIC(15,2) NOT NULL,
    FORMA_PAGTO SMALLINT,
    OBSERVACAO D_DESCRICAO);

ALTER TABLE CONTA_PAGAR
ADD CONSTRAINT PK_CONTA_PAGAR
PRIMARY KEY (ID);

COMMENT ON COLUMN CONTA_PAGAR.VALOR_TOTAL IS
'Valor total da conta';

COMMENT ON COLUMN CONTA_PAGAR.FORMA_PAGTO IS
'1 - Transferencia Bancaria
2 - Debito em Conta
3 - Cartao de Credito
4 - Cartao de Debito
5 - Cheque
6 - Outro';

CREATE SEQUENCE GEN_CONTA_PAGAR;



ALTER TABLE CONTA_PAGAR
    ALTER NOME TO DESCRICAO;



CREATE TABLE CONTA_PAGAR_PARCELA (
    ID INTEGER NOT NULL,
    ID_CONTA_PAGAR INTEGER NOT NULL,
    VENCIMENTO DATE NOT NULL,
    VALOR NUMERIC(15,2) NOT NULL,
    PARCELA SMALLINT NOT NULL);

ALTER TABLE CONTA_PAGAR_PARCELA
ADD CONSTRAINT PK_CONTA_PAGAR_PARCELA
PRIMARY KEY (ID);

COMMENT ON COLUMN CONTA_PAGAR_PARCELA.PARCELA IS
'Numero da parcela';

CREATE SEQUENCE GEN_CONTA_PAGAR_PARCELA;



ALTER TABLE CONTA_PAGAR_PARCELA
ADD CONSTRAINT FK_CONTA_PAGAR_PARCELA_1
FOREIGN KEY (ID_CONTA_PAGAR)
REFERENCES CONTA_PAGAR(ID)
ON DELETE CASCADE
ON UPDATE CASCADE;



ALTER TABLE CONTA_PAGAR
ADD CONSTRAINT FK_CONTA_PAGAR_1
FOREIGN KEY (ID_FORNECEDOR)
REFERENCES FIN_FOR_CLI(ID)
ON UPDATE CASCADE;

ALTER TABLE CONTA_PAGAR
ADD CONSTRAINT FK_CONTA_PAGAR_2
FOREIGN KEY (ID_RUBRICA)
REFERENCES RUBRICA(ID)
ON UPDATE CASCADE;

ALTER TABLE CONTA_PAGAR
ADD CONSTRAINT FK_CONTA_PAGAR_3
FOREIGN KEY (ID_PLANO_CONTAS)
REFERENCES PLANO_CONTAS(ID)
ON UPDATE CASCADE;

ALTER TABLE CONTA_PAGAR
ADD CONSTRAINT FK_CONTA_PAGAR_4
FOREIGN KEY (ID_CONTA_CORRENTE)
REFERENCES BANCO_CONTA_CORRENTE(ID)
ON UPDATE CASCADE;



CREATE TABLE CONTA_PAGAR_PROJETO (
    ID INTEGER NOT NULL,
    ID_CONTA_PAGAR INTEGER NOT NULL,
    ID_PROJETO INTEGER NOT NULL);

ALTER TABLE CONTA_PAGAR_PROJETO
ADD CONSTRAINT PK_CONTA_PAGAR_PROJETO
PRIMARY KEY (ID);

CREATE SEQUENCE GEN_CONTA_PAGAR_PROJETO;



ALTER TABLE CONTA_PAGAR_PROJETO
ADD CONSTRAINT FK_CONTA_PAGAR_PROJETO_1
FOREIGN KEY (ID_CONTA_PAGAR)
REFERENCES CONTA_PAGAR(ID)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE CONTA_PAGAR_PROJETO
ADD CONSTRAINT FK_CONTA_PAGAR_PROJETO_2
FOREIGN KEY (ID_PROJETO)
REFERENCES PROJETO(ID)
ON UPDATE CASCADE;



CREATE TABLE CONTA_PAGAR_ATIVIDADE (
    ID INTEGER NOT NULL,
    ID_CONTA_PAGAR INTEGER NOT NULL,
    ID_ATIVIDADE INTEGER NOT NULL);

ALTER TABLE CONTA_PAGAR_ATIVIDADE
ADD CONSTRAINT PK_CONTA_PAGAR_ATIVIDADE
PRIMARY KEY (ID);

CREATE SEQUENCE GEN_CONTA_PAGAR_ATIVIDADE;



ALTER TABLE CONTA_PAGAR_ATIVIDADE
ADD CONSTRAINT FK_CONTA_PAGAR_ATIVIDADE_1
FOREIGN KEY (ID_CONTA_PAGAR)
REFERENCES CONTA_PAGAR(ID)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE CONTA_PAGAR_ATIVIDADE
ADD CONSTRAINT FK_CONTA_PAGAR_ATIVIDADE_2
FOREIGN KEY (ID_ATIVIDADE)
REFERENCES ATIVIDADE(ID)
ON UPDATE CASCADE;



DROP SEQUENCE GEN_AREA_CUSTO;

delete from projeto_financiador;

ALTER TABLE PROJETO_FINANCIADOR DROP CONSTRAINT FK_PROJETO_FINANCIADOR_2;

ALTER TABLE PROJETO_FINANCIADOR
ADD CONSTRAINT FK_PROJETO_FINANCIADOR_2
FOREIGN KEY (ID_FINANCIADOR)
REFERENCES FIN_FOR_CLI(ID)
ON UPDATE CASCADE;



DROP TABLE FINANCIADOR;



DROP SEQUENCE GEN_FINANCIADOR;



DROP SEQUENCE GEN_RUBRICA_PROJETO;



update RDB$RELATION_FIELDS set
RDB$NULL_FLAG = 1
where (RDB$FIELD_NAME = 'CPF_CNPJ') and
(RDB$RELATION_NAME = 'FIN_FOR_CLI')
;



update RDB$RELATION_FIELDS set
RDB$NULL_FLAG = 1
where (RDB$FIELD_NAME = 'TIPO') and
(RDB$RELATION_NAME = 'FIN_FOR_CLI')
;



ALTER TABLE FIN_FOR_CLI DROP CONSTRAINT UNQ1_FIN_FOR_CLI;



ALTER TABLE FIN_FOR_CLI DROP CONSTRAINT UNQ3_FIN_FOR_CLI;

ALTER TABLE FIN_FOR_CLI
ADD CONSTRAINT UNQ3_FIN_FOR_CLI
UNIQUE (NOME_FANTASIA,RAZAO_SOCIAL,TIPO)
USING INDEX UNQ3_FIN_FOR_CLI;



COMMENT ON COLUMN CONTA_PAGAR.FORMA_PAGTO IS
'1 - Transferencia Bancaria
2 - Debito em Conta
3 - Cartao de Credito
4 - Cartao de Debito
5 - Cheque
6 - Em Especie
7 - Outro';



ALTER TABLE CONTA_RECEBER DROP ID_CLIENTE;



ALTER TABLE CONTA_RECEBER
    ADD ID_CLIENTE_FINANCIADOR INTEGER NOT NULL;

COMMENT ON COLUMN CONTA_RECEBER.ID_CLIENTE_FINANCIADOR IS
'Id do cliente ou do financiador que irão realizar o pagamento';

alter table CONTA_RECEBER
alter ID position 1;

alter table CONTA_RECEBER
alter ID_CLIENTE_FINANCIADOR position 2;

alter table CONTA_RECEBER
alter ID_PLANO_CONTAS position 3;

alter table CONTA_RECEBER
alter ID_CONTA_CORRENTE position 4;

alter table CONTA_RECEBER
alter DESCRICAO position 5;

alter table CONTA_RECEBER
alter VALOR_TOTAL position 6;

alter table CONTA_RECEBER
alter FORMA_PAGTO position 7;

alter table CONTA_RECEBER
alter OBSERVACAO position 8;



ALTER TABLE CONTA_RECEBER
ADD CONSTRAINT FK_CONTA_RECEBER_1
FOREIGN KEY (ID_CLIENTE_FINANCIADOR)
REFERENCES FIN_FOR_CLI(ID)
ON UPDATE CASCADE;



ALTER TABLE CONTA_RECEBER_PARCELA
    ADD STATUS SMALLINT,
    ADD DATA_RECEBIMENTO DATE;

COMMENT ON COLUMN CONTA_RECEBER_PARCELA.STATUS IS
'0|NULL - Em aberto
1 - Recebida';



ALTER TABLE CONTA_PAGAR_PARCELA
    ADD STATUS SMALLINT,
    ADD DATA_PAGAMENTO DATE;

COMMENT ON COLUMN CONTA_PAGAR_PARCELA.STATUS IS
'0|NULL - Em aberto
1 - Pago';



ALTER TABLE FIN_FOR_CLI DROP PESQUISA;



ALTER TABLE LOTE_MUDA
    ADD TAXA_CLASSIFICACAO NUMERIC(15,2);

COMMENT ON COLUMN LOTE_MUDA.TAXA_CLASSIFICACAO IS
'Taxa que informa a porcentagem de mudas que foram aproveitas.
Formula para calculo
Qtde Atual de Mudas * 100)/Qtde. Inicial de Mudas';



ALTER TABLE CONTA_PAGAR
    ADD NUMERO_DOCUMENTO VARCHAR(30);



ALTER TABLE CONTA_RECEBER
    ADD NUMERO_DOCUMENTO VARCHAR(30);

